### PR TITLE
Improve clarity that the dashboard is loading data and not broken

### PR DESCRIPTION
**Pull request by gitstart**
### What does this PR do?

-  It improves clarity that the dashboard is loading data and not broken

### Issue reference 

-  https://github.com/filecoin-saturn/L1-dashboard/issues/39

### Demo video/scrennshot:

-  https://jam.dev/c/0c90672a-b2f8-41ce-864b-0270d1ebfcda

### CODE REVIEW

**Comment by gitstart** [comment]
This PR is a refrence to https://github.com/GitStartHQ/client-filecoin-saturn/issues/1

**Comment by gitstart** [comment]
@guanzo @joaosa @DiegoRBaquero this PR is ready for review

**Comment by gitstart** [comment]
Hello nice to meet you. We are GitStart building a service for engineering teams to assign tickets and get back PRs. We'd appreciate if you'd read our PR.
If at first glance it doesn't look at all like something you'd merge, please simply send us a "nope" and we'll figure out why ourselves with the help of our mentors. Our goal is for you not to spend time on totally off-road PRs.
However if the PR interests you, please proceed like you always do.
You can always reach us via [support@gitstart.com](mailto:support@gitstart.com) for any feedback or questions. Thank you!

**Comment by guanzo** [comment]
On the top right chart, "No Rows To Show" should be replaced with a loading spinner when it's loading.

The top left chart looks a bit weird because the loading icon is off center. My suggestion is to hide the text while loading, and put the loading icon in the center. When it's done loading, make the text visible again.

Basically, all charts should look similar while loading, mainly the loading icon should be centered.

**Comment by gitstart** [comment]
> On the top right chart, "No Rows To Show" should be replaced with a loading spinner when it's loading.
> 
> The top left chart looks a bit weird because the loading icon is off center. My suggestion is to hide the text while loading, and put the loading icon in the center. When it's done loading, make the text visible again.
> 
> Basically, all charts should look similar while loading, mainly the loading icon should be centered.

We're on it

**Comment by gitstart** [comment]
> On the top right chart, "No Rows To Show" should be replaced with a loading spinner when it's loading.
> 
> The top left chart looks a bit weird because the loading icon is off center. My suggestion is to hide the text while loading, and put the loading icon in the center. When it's done loading, make the text visible again.
> 
> Basically, all charts should look similar while loading, mainly the loading icon should be centered.

Loom video for the new updates pushed https://www.loom.com/share/f6860500e0f1420dbf54be274f7efea5?sid=471fe11e-2497-4e3d-9619-a85b6065c3a4

**Comment by guanzo** [comment]
looks great, thanks!

**Pull request merged**
